language: csharp
solution: ZTestExtractor.sln
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore ZTestExtractor.sln
after_script:
  - nunit-console ZTestExtractor.Business.Test/bin/Release/ZTestExtractor.Business.Test.dll